### ISSUE TITLE
Pie charts on numbers page disappear after mouse hover

### ISSUE THREAD

**Issue by sasha42** [der-michik/c3bottles#46]
When a user hovers over the pie charts on the `/numbers` page, the pie charts disappear until the user reloads the page:
![c3bottles-chart-error](https://cloud.githubusercontent.com/assets/1775702/12030580/3d891b6e-ae01-11e5-9a89-592825a5b3eb.gif)

I was able to reproduce this error on the following browsers:
- Chrome 49.0.2604.0 canary clean (64-bit mac)
- Chrome 49.0.2573.0 chromium with lots of plugins (64-bit mac)
- Safari 9.0.2 (10601.3.9 mac)
- Chrome 47.0.2526.83 Android 4.4.4

I was unable to reproduce this error on Internet Explorer 8 - the charts didn't load.

**Comment by der-michik** [comment]
Looks like some issue with chart.js to me on the first glance. In addition to them disapperaring, the pie charts should be colored according to the legend in the middle. I think I will switch the JS lib to draw the charts since chart.js can't do the things I originally wanted to do (and planned to add later) anyway.

Everything works fine in Firefox on the desktop and mobile by the way.
